DROP DATABASE IF EXISTS chemister;

DROP TYPE IF EXISTS bid_status;
DROP TYPE IF EXISTS bid_type;

DROP TABLE IF EXISTS config CASCADE;
DROP TABLE IF EXISTS bid CASCADE;
DROP TABLE IF EXISTS resource CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP ROLE IF EXISTS "che";
