---

# not needed, just an example of including top-level vars
- include_vars: "common.yml"
- include_vars: "vars/vault.yml"
  no_log: true

- name: install postgres
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-server
    - postgresql-contrib
  become: true

- name: create new database cluster
  shell: "postgresql-setup initdb"
  args:
    creates: "/var/lib/pgsql/data"
  register: pg_initdb
  become: true

- name: set password to postgres user
  shell: |
    sudo -u postgres psql \
    -c "ALTER USER postgres with password '{{ postgres_default_pass }}';"
  no_log: true  # no password in output
  when: pg_initdb is defined and pg_initdb.changed
  become: true

- name: copy configuration file
  copy:
    src: "files/pg_hba.conf"
    dest: "/var/lib/pgsql/data/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  register: pg_config
  become: true

- name: restart postgres service
  systemd:
    name: postgresql
    state: restarted
  when: pg_config.changed
  become: true

- name: enable postgres service
  systemd:
    name: postgresql
    state: started
    enabled: true
  become: true
