---

# not needed, just an example of including top-level vars
- include_vars: "common.yml"

- name: install postgres
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-server
    - postgresql-contrib
  become: true

- name: create new database cluster
  shell: "postgresql-setup initdb"
  args:
    creates: "/var/lib/pgsql/data"
  become: true

- postgresql_user:
    db: postgres
    name: postgres
    password: "{{ postgres_default_pass }}"
    expire: infinity
  become: true

- name: copy configuration file
  copy:
    src: "files/pg_hba.conf"
    dest: "/var/lib/pgsql/data/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0600
  notify: restart postgres
  become: true

- name: enable postgres service
  systemd:
    name: postgresql
    state: started
    enabled: true
  become: true
