---
- hosts: all

  tasks:

    - include_vars: "vars/common.yml"

    - name: create project directory
      file:
        path: "{{ project_root }}"
        state: directory
        mode: 0755
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
      become: true

    - name: clone project repository
      git:
        repo: "{{ repository_url }}"
        dest: "{{ project_root }}"
        version: "{{ repository_branch }}"
        accept_hostkey: true


    - name:
